"""Documentation agent.

Aggregates every artifact the closed loop produces — specification, architecture,
design-space exploration, design review, generated RTL, HDL review, verification,
formal checks, simulation status, debugging history, the QoR refinement loop,
optimization proposals, synthesis status, and per-stage confidence — into one
Markdown engineering report. Wording policy: every claim in the report names its
evidence and its source (measured vs estimated, tool-run vs model-only); see
docs/CLAIMS.md.

PDF export is left as an optional downstream step (`pandoc report.md -o report.pdf`)
so the core tool carries no heavyweight rendering dependency.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .base import Agent
from .architecture_agent import Architecture
from .critic_agent import Finding
from .hdl_critic_agent import HDLReview
from .verification_agent import VerificationResult
from .debug_agent import DebugReport
from .optimization_agent import OptimizationReport
from .formal_agent import FormalResult
from ..core.project import Project
from ..core.spec import Specification
from ..core.context import EngineeringContext
from ..hdl.library import GeneratedDesign
from ..sim.runner import SimulationResult
from ..sim.synth import SynthResult


class DocumentationAgent(Agent):
    name = "documentation"

    def run(self, project: Project, spec: Specification, arch: Architecture,
            design: GeneratedDesign, findings: list[Finding],
            hdl_review: HDLReview, vres: VerificationResult, sim: SimulationResult,
            debug: DebugReport, opt: OptimizationReport, formal: FormalResult,
            synth: SynthResult, ctx: EngineeringContext) -> Path:
        md = self._report(project, spec, arch, design, findings, hdl_review,
                          vres, sim, debug, opt, formal, synth, ctx)
        path = project.write(f"reports/{spec.name}_report.md", md, "report")
        self.log(project, f"engineering report written -> reports/{spec.name}_report.md",
                 "success")
        return path

    # ------------------------------------------------------------------
    def _report(self, project, spec, arch, design, findings, hdl_review,
                vres, sim, debug, opt, formal, synth, ctx) -> str:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        L: list[str] = []
        w = L.append

        w(f"# Engineering Report — {spec.title}")
        w("")
        w(f"*Generated by AI FPGA Engineer on {ts}.*")
        w("")
        w(f"> Overall confidence **{ctx.overall_confidence():.2f}** "
          "(evidence-derived; see docs/CLAIMS.md). "
          f"RTL simulation (GHDL): **{'ran' if sim.ran else 'NOT run in this environment'}**. "
          f"QoR source: **{ctx.qor.source if ctx.qor else 'n/a'}**. "
          "Model-level checks validate the reference oracle; only tool-backed rows "
          "below make claims about the emitted VHDL.")
        w("")

        w("## 1. Request")
        w("")
        w("```")
        w((project.request or spec.source_request).strip())
        w("```")
        w("")

        w("## 2. Specification")
        w("")
        w(f"- **Design class:** `{spec.design_class}`")
        w(f"- **Data width:** {spec.data_width} bits")
        w(f"- **Clocking:** {spec.clocking}")
        w("")
        w("| Port | Dir | Width | Role |")
        w("|------|-----|-------|------|")
        for p in spec.ports:
            w(f"| `{p.name}` | {p.direction} | {p.width} | {p.role} |")
        w("")
        if spec.operations:
            w("Operations: " + ", ".join(f"`{o.name}`" for o in spec.operations) + ".")
            w("")

        w("## 3. Architecture")
        w("")
        w(arch.summary)
        w("")
        w(f"- **Style:** {arch.style}")
        if arch.blocks:
            w(f"- **Blocks:** {', '.join(arch.blocks)}")
        w(f"- **Chosen implementation contract:** `{design.decisions.label()}`")
        w("")

        w("## 4. Design-Space Exploration")
        w("")
        if ctx.candidates:
            w("The architecture is a binding contract consumed by the HDL generator, so "
              "each candidate below produces *different* RTL. They were estimated and "
              "ranked; the selected one drove generation.")
            w("")
            w("| Architecture | LUTs | Regs | Fmax (MHz) | Selected |")
            w("|--------------|------|------|------------|:--------:|")
            for c in ctx.candidates:
                w(f"| {c.decisions.label()} | {c.qor.luts} | {c.qor.registers} | "
                  f"{c.qor.fmax_mhz} | {'yes' if c.selected else ''} |")
            w("")
        else:
            w("Single architecture for this class; no exploration needed.")
            w("")

        w("## 5. Architecture Review")
        w("")
        blocking = [f for f in findings if f.severity == "block"]
        if not findings:
            w("The architecture critic raised no findings.")
        else:
            w("| Severity | Rule | Finding |")
            w("|----------|------|---------|")
            for f in findings:
                w(f"| {f.severity} | `{f.rule}` | {f.message} |")
            w("")
            w(f"Blocking findings: **{len(blocking)}**.")
        w("")

        w("## 6. Generated RTL & HDL Review")
        w("")
        w(f"Entity `{design.entity}` ({design.kind}, latency {design.latency} clock(s)) "
          f"was generated as synthesizable VHDL-2008 reflecting the chosen architecture, "
          f"then reviewed at the RTL level *before* verification.")
        w("")
        if design.opcode_map:
            w("Opcode encoding (" + design.decisions.opcode_encoding + "): " +
              ", ".join(f"{k}=`{v}`" for k, v in design.opcode_map.items()) + ".")
            w("")
        if not hdl_review.findings:
            w("HDL review: no issues; RTL is synthesizable and structurally sound.")
        else:
            w("HDL review findings:")
            w("")
            w("| Severity | Rule | Finding |")
            w("|----------|------|---------|")
            for f in hdl_review.findings:
                w(f"| {f.severity} | `{f.rule}` | {f.message} |")
            w("")
            w(f"Blocking: **{len(hdl_review.blocking)}** "
              f"({'all repaired' if hdl_review.clean else 'unresolved'}).")
        w("")

        w("## 7. Verification")
        w("")
        w(f"- **Test vectors:** {vres.total}")
        w(f"- **Reference-model property checks:** "
          f"{'PASS' if not vres.property_failures else 'FAIL'} "
          f"({len(vres.property_failures)} violation(s))")
        w(f"- **Self-checking testbench:** `tb/{vres.tb_entity}.vhd`")
        w("")
        w("The testbench embeds expected values from the spec-derived reference "
          "oracle, so a passing GHDL run establishes RTL/oracle agreement on every "
          "embedded vector. Whether GHDL actually ran is reported in section 9.")
        w("")

        w("## 8. Formal Verification")
        w("")
        if formal.properties:
            w(f"**{formal.label()}.** Model checks (software, on the oracle) are listed "
              "below; the SymbiYosys row is the only line that speaks about the emitted RTL.")
            w("")
            w("| Property | Status | Method |")
            w("|----------|--------|--------|")
            for p in formal.properties:
                w(f"| `{p.name}` | {p.status} | {p.method} |")
            w("")
            w(f"RTL-level BMC status: **{formal.sby_status}** "
              f"(`sby -f {Path(formal.sby_path).name}`, depth-bounded).")
        else:
            w("Formal stage skipped for this run.")
        w("")

        w("## 9. Simulation")
        w("")
        if sim.ran:
            w(f"GHDL executed the testbench: **{'PASSED' if sim.passed else 'FAILED'}** "
              f"(backend {sim.backend}).")
        else:
            w("GHDL is not installed in this environment, so **the RTL itself was not "
              "executed**; a ready-to-run flow was emitted:")
            w("")
            w("```bash")
            w("cd tb && ./run_ghdl.sh      # or: make sim")
            w("```")
            w("")
            w(f"In-container reference-model status: **{'PASS' if vres.passed else 'FAIL'}** "
              f"over {vres.total} vectors (model-level only).")
        w("")

        w("## 10. Autonomous Debugging")
        w("")
        if debug.steps:
            w(f"The repair loop ran {debug.iterations} iteration(s):")
            w("")
            w("| # | Defect | Action | Resolved |")
            w("|---|--------|--------|:--------:|")
            for s in debug.steps:
                w(f"| {s.iteration} | `{s.defect}` | {s.action} | "
                  f"{'yes' if s.resolved else 'no'} |")
            w("")
            w(f"Final state: **{'clean' if debug.final_clean else 'unresolved'}**. "
              "Repairs are limited to mechanically fixable defect classes; semantic "
              "defects are diagnosed and flagged, never silently 'fixed'.")
        else:
            w("No defects required correction; the generated RTL passed the gate on the "
              "first attempt.")
        w("")

        w("## 11. Quality-of-Results Loop")
        w("")
        if ctx.qor_history:
            w("Each pass measured QoR against the targets (the `source` column says "
              "whether numbers are place-and-route measurements or heuristic "
              "estimates); when unmet, the optimizer proposed the next architecture "
              "and the design was regenerated.")
            w("")
            w("| Iter | Architecture | LUTs | Regs | Fmax (MHz) | Source | Action applied | Targets met |")
            w("|:----:|--------------|------|------|------------|--------|----------------|:-----------:|")
            for q in ctx.qor_history:
                w(f"| {q.iteration} | {q.decisions.label()} | {q.qor.luts} | "
                  f"{q.qor.registers} | {q.qor.fmax_mhz} | {q.qor.source} | {q.action} | "
                  f"{'yes' if q.met else '—'} |")
            w("")
        else:
            w("No QoR targets were set, so the loop ran a single generation pass.")
            w("")

        w("## 12. Optimization")
        w("")
        cur = opt.current
        w(f"Final design QoR (estimated, ranking only): **{cur.luts} LUTs, "
          f"{cur.registers} registers, critical path {cur.critical_path_ns} ns, "
          f"Fmax≈{cur.fmax_mhz} MHz**. "
          f"Best architecture for the objective: **{opt.best}**.")
        w("")
        if opt.proposals:
            w("Actionable proposals (machine-readable; each regenerates the RTL):")
            w("")
            w("| Change | Est. gain | Rationale |")
            w("|--------|-----------|-----------|")
            for p in opt.proposals:
                w(f"| `{p.kind}` | {p.est_gain} | {p.rationale} |")
            w("")
        else:
            w("The current architecture is already best for this objective.")
            w("")

        w("## 13. Synthesis")
        w("")
        if synth.ran and synth.qor is not None:
            fm = f", Fmax {synth.qor.fmax_mhz} MHz" if synth.qor.fmax_mhz else ""
            w(f"Measured ({synth.backend}): **{synth.qor.luts} LUTs, "
              f"{synth.qor.registers} FFs{fm}** (source `{synth.qor.source}`).")
        else:
            w("No synthesis tool present; a runnable Yosys/nextpnr flow was emitted under "
              "`synth/` so real cell counts and timing can be obtained on your machine "
              "and fed back into the optimization loop.")
        w("")

        w("## 14. Confidence")
        w("")
        w("Scores are derived from evidence (what actually ran and passed); 1.0 on a "
          "tool-backed stage means the real tool executed and passed. Formulas: "
          "docs/CLAIMS.md.")
        w("")
        w("| Stage | Confidence |")
        w("|-------|:----------:|")
        for stage, c in ctx.confidence.items():
            w(f"| {stage} | {c:.2f} |")
        w("")
        w(f"**Overall (weakest stage): {ctx.overall_confidence():.2f}.**")
        if ctx.low_confidence_stages():
            w("")
            w("Low-confidence stages flagged for review: " +
              ", ".join(ctx.low_confidence_stages()) + ".")
        w("")

        w("## 15. Artifact Index")
        w("")
        w("| Label | Path |")
        w("|-------|------|")
        for label, rel in sorted(project.artifacts.items()):
            w(f"| {label} | `{rel}` |")
        w("")
        w("---")
        w("")
        w("*AI FPGA Engineer — rule-based closed-loop specification-to-verified-RTL pipeline.*")
        return "\n".join(L)
