"""Generate the research website from repository artifacts.

Emits a static, dependency-free multi-page site under ``website/`` whose data
(leaderboards, figures, benchmark catalogue, experiment summary) is copied from
``results/`` and the benchmark suite — never hand-duplicated. Pages: Home,
Architecture, Pipeline, Benchmarks, Experiments, Results, Future Work.
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
WEB = ROOT / "website"
RESULTS = ROOT / "results"
EXP = "baseline-v1"

from hdleval.benchmarks.difficulty import difficulty_tier  # noqa: E402
from hdleval.benchmarks.loader import load_suite  # noqa: E402

_CSS = """
:root{--bg:#0f1226;--card:#1a1f3a;--ink:#e8e8f0;--accent:#e94560;--muted:#9aa0c0}
*{box-sizing:border-box}body{margin:0;font-family:system-ui,Arial;background:var(--bg);color:var(--ink)}
nav{display:flex;gap:1rem;padding:1rem 2rem;background:#0a0c1a;position:sticky;top:0;flex-wrap:wrap}
nav a{color:var(--ink);text-decoration:none;font-weight:600}nav a:hover{color:var(--accent)}
main{max-width:1000px;margin:0 auto;padding:2rem}
h1,h2{color:#fff}a{color:var(--accent)}
.card{background:var(--card);border-radius:12px;padding:1.2rem 1.5rem;margin:1rem 0}
table{border-collapse:collapse;width:100%;margin:1rem 0}th,td{border:1px solid #333;padding:.5rem;text-align:left}
th{background:#0a0c1a}.tag{display:inline-block;background:#0a0c1a;color:var(--muted);
padding:.1rem .5rem;border-radius:6px;margin:.1rem;font-size:.8rem}
img{max-width:100%;background:#fff;border-radius:8px}
.hero{font-size:1.1rem;color:var(--muted)}
"""

NAV = """<nav>
<a href="index.html">Home</a><a href="architecture.html">Architecture</a>
<a href="pipeline.html">Pipeline</a><a href="benchmarks.html">Benchmarks</a>
<a href="experiments.html">Experiments</a><a href="results.html">Results</a>
<a href="future.html">Future Work</a></nav>"""


def page(title: str, body: str) -> str:
    return (f"<!doctype html><html><head><meta charset='utf-8'><title>{title} · hdleval</title>"
            f"<meta name='viewport' content='width=device-width,initial-scale=1'>"
            f"<style>{_CSS}</style></head><body>{NAV}<main>{body}</main></body></html>")


def main() -> None:
    WEB.mkdir(parents=True, exist_ok=True)
    (WEB / "assets").mkdir(exist_ok=True)
    (WEB / "data").mkdir(exist_ok=True)

    # copy figures + data
    figdir = RESULTS / "figures"
    if figdir.exists():
        for svg in figdir.glob("*.svg"):
            shutil.copy2(svg, WEB / "assets" / svg.name)
    lb_path = RESULTS / "leaderboards" / f"{EXP}_leaderboard.json"
    lb = json.loads(lb_path.read_text()) if lb_path.exists() else {"overall": [], "by_category": {}, "by_difficulty": {}}
    shutil.copy2(lb_path, WEB / "data" / "leaderboard.json") if lb_path.exists() else None

    suite = load_suite("v1")
    (WEB / "data" / "benchmarks.json").write_text(
        json.dumps([b.to_dict() for b in suite], indent=2))

    # Home
    (WEB / "index.html").write_text(page("Home", f"""
<h1>hdleval</h1>
<p class='hero'>An extensible, reproducible platform for evaluating LLM-assisted
hardware design.</p>
<div class='card'><b>{len(suite)}</b> versioned benchmarks · 7 categories ·
config-driven harness · every artifact regenerated by <code>reproduce.py</code>.</div>
<div class='card'><h2>What it is</h2><p>hdleval treats AI-assisted hardware design
as a measurable science: a fixed evaluation harness, a versioned benchmark
taxonomy, quantitative metrics beyond pass/fail, an experiment registry with full
provenance, and automatically generated leaderboards, reports and figures.</p></div>
<p><a href='results.html'>See the latest results &rarr;</a></p>"""))

    # Architecture
    (WEB / "architecture.html").write_text(page("Architecture", """
<h1>Architecture</h1>
<div class='card'><p>Layered and plugin-based: configuration → model providers →
prompt strategies → HDL parsing → benchmark suite → toolchain adapters
(GHDL/Yosys) → metrics → evaluation harness → experiment registry → leaderboard →
reporting. Model inference is injected; adding a model never changes evaluation
logic.</p></div>
<pre class='card'>configs/ ─▶ hdleval.config
                 │
 models/ ─▶ ModelProvider ─┐
 prompts/ ─▶ PromptStrategy ├─▶ EvaluationHarness ─▶ ExperimentDB ─▶ Leaderboard ─▶ Reports
 benchmarks/v1 ─▶ Suite ────┘                                   └─▶ Figures / Website</pre>"""))

    # Pipeline
    (WEB / "pipeline.html").write_text(page("Pipeline", """
<h1>Evaluation pipeline</h1>
<div class='card'><p>Every benchmark, for every model, follows one identical
procedure:</p>
<pre>load spec ▶ build prompt ▶ infer ▶ parse ▶ compile ▶ synthesize
        ▶ simulate ▶ metrics ▶ properties ▶ classify ▶ record</pre>
<p>Toolchain stages degrade to <code>skipped</code> when a tool is absent, so the
pipeline runs anywhere and is strict in CI.</p></div>"""))

    # Benchmarks
    rows = "".join(
        f"<tr><td>{b.id}</td><td>{b.category}</td><td>{b.estimated_difficulty} "
        f"({difficulty_tier(b.estimated_difficulty)})</td><td>{b.title}</td>"
        f"<td>{''.join(f'<span class=tag>{t}</span>' for t in b.tags)}</td></tr>"
        for b in suite)
    (WEB / "benchmarks.html").write_text(page("Benchmarks", f"""
<h1>Benchmark suite (v1)</h1>
<p>{len(suite)} benchmarks across 7 categories, each with structured metadata,
an objective difficulty score and a verified reference implementation.</p>
<table><tr><th>ID</th><th>Category</th><th>Difficulty</th><th>Title</th><th>Tags</th></tr>
{rows}</table>
<p><a href='data/benchmarks.json'>Download benchmark metadata (JSON)</a></p>"""))

    # Experiments
    (WEB / "experiments.html").write_text(page("Experiments", """
<h1>Experiments</h1>
<div class='card'><h2>baseline-v1</h2><p>Reference (upper bound) vs three
synthetic-fidelity baselines across the full suite, 3 trials each. Establishes
the measurement machinery independent of any model API.</p></div>
<div class='card'><h2>model-comparison-v1</h2><p>A real model (Anthropic) vs a
synthetic baseline through the identical harness (requires API key).</p></div>
<div class='card'><h2>prompt-ablation-v1</h2><p>Direct vs chain-of-thought vs
self-repair prompting on a fixed model.</p></div>"""))

    # Results
    def tbl(rows, cols):
        if not rows:
            return "<p>run <code>reproduce.py</code> to populate.</p>"
        h = "<tr>" + "".join(f"<th>{c}</th>" for c in cols) + "</tr>"
        b = "".join("<tr>" + "".join(f"<td>{r.get(c,'')}</td>" for c in cols) + "</tr>" for r in rows)
        return f"<table>{h}{b}</table>"

    figs = "".join(f"<img src='assets/{p.name}' alt='{p.stem}'>"
                   for p in sorted((WEB / "assets").glob("*.svg")))
    (WEB / "results.html").write_text(page("Results", f"""
<h1>Results — baseline-v1</h1>
<h2>Overall leaderboard</h2>
{tbl(lb['overall'], ['model','prompt','n','pass_rate','pass_ci95','compile_rate','avg_latency_s','avg_tokens'])}
<h2>Figures</h2>{figs}
<p><a href='data/leaderboard.json'>Download leaderboard (JSON)</a> ·
<a href='../results/reports/{EXP}_report.md'>Markdown report</a></p>"""))

    # Future work
    (WEB / "future.html").write_text(page("Future Work", """
<h1>Future work</h1>
<div class='card'><ul>
<li>Multi-model benchmarking with real APIs and significance testing</li>
<li>Formal equivalence checking and property proof backends</li>
<li>Retrieval-augmented generation over vendor/protocol docs</li>
<li>Reinforcement-learning optimization of prompting and self-repair</li>
<li>Open benchmark dataset release (Hugging Face)</li>
<li>Generalisation beyond VHDL: Verilog, SystemVerilog, Chisel, HLS</li>
</ul></div>"""))

    print("website written to", WEB)


if __name__ == "__main__":
    main()
