"""Measured QoR via a real place-and-route flow (iCE40 UP5K)."""
from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path

from ..core.decisions import QoR
from ..core import toolchain
from ..hdl.library import GeneratedDesign

DEVICE = "up5k"
SEED = 1
FREQ_TARGET_MHZ = 40   # placement target only; achieved Fmax is what we report


@dataclass
class PnrResult:
    ran: bool
    qor: QoR | None = None
    log: str = ""
    reason: str = ""            # why it did not run, if it didn't
    harness_path: str = ""
    report_path: str = ""


def available() -> tuple[bool, str]:
    tc = toolchain.detect()
    if not tc.present.get("yosys"):
        return False, "yosys not installed"
    if not tc.ghdl_plugin:
        return False, "yosys GHDL plugin not available"
    if not tc.present.get("nextpnr-ice40"):
        return False, "nextpnr-ice40 not installed"
    return True, ""


# ---------------------------------------------------------------------------
# Timing harness generation
# ---------------------------------------------------------------------------
def timing_harness_vhdl(design: GeneratedDesign) -> str:
    e = design.entity
    ins = [p for p in design.ports if p.direction == "in" and p.role != "clock"]
    outs = [p for p in design.ports if p.direction == "out"]
    has_clk = any(p.role == "clock" for p in design.ports)
    nin = sum(p.width for p in ins)
    nout = sum(p.width for p in outs)

    sig_decls, in_assigns, out_collect, port_assoc = [], [], [], []
    if has_clk:
        port_assoc.append("clk => clk")
    bit = 0
    for p in ins:
        if p.width == 1:
            sig_decls.append(f"    signal s_{p.name} : std_logic;")
            in_assigns.append(f"    s_{p.name} <= sr({bit});")
        else:
            sig_decls.append(f"    signal s_{p.name} : std_logic_vector({p.width - 1} downto 0);")
            in_assigns.append(f"    s_{p.name} <= sr({bit + p.width - 1} downto {bit});")
        port_assoc.append(f"{p.name} => s_{p.name}")
        bit += p.width
    obit = 0
    for p in outs:
        if p.width == 1:
            sig_decls.append(f"    signal s_{p.name} : std_logic;")
            out_collect.append(f"    obus({obit}) <= s_{p.name};")
        else:
            sig_decls.append(f"    signal s_{p.name} : std_logic_vector({p.width - 1} downto 0);")
            out_collect.append(f"    obus({obit + p.width - 1} downto {obit}) <= s_{p.name};")
        port_assoc.append(f"{p.name} => s_{p.name}")
        obit += p.width
    assoc = ",\n             ".join(port_assoc)

    return f"""library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Timing-measurement harness for {e} (generated by AI FPGA Engineer).
-- Serial-in shift register drives all DUT inputs; DUT outputs are registered
-- and XOR-reduced to one pin, so nextpnr times the DUT's combinational depth
-- as a reg-to-reg path regardless of DUT width or pin budget.
entity {e}_timed is
    port (
        clk : in  std_logic;
        si  : in  std_logic;
        so  : out std_logic
    );
end entity {e}_timed;

architecture harness of {e}_timed is
    signal sr   : std_logic_vector({max(nin, 1) - 1} downto 0) := (others => '0');
    signal obus : std_logic_vector({max(nout, 1) - 1} downto 0);
    signal oreg : std_logic_vector({max(nout, 1) - 1} downto 0) := (others => '0');
{chr(10).join(sig_decls)}
begin
    -- input capture: serial shift so top-level I/O never limits DUT width
    process(clk)
    begin
        if rising_edge(clk) then
            sr   <= sr(sr'high - 1 downto 0) & si;
            oreg <= obus;   -- output capture: DUT outputs land in registers
        end if;
    end process;
{chr(10).join(in_assigns)}

    dut: entity work.{e}
        port map ({assoc});

{chr(10).join(out_collect)}
    so <= xor oreg;   -- VHDL-2008 unary reduction; short post-register path
end architecture harness;
"""


# ---------------------------------------------------------------------------
# Flow execution and parsing
# ---------------------------------------------------------------------------
def run_ice40(project, design: GeneratedDesign, timeout: int = 600) -> PnrResult:
    ok, why = available()
    if not ok:
        return PnrResult(False, reason=why)

    e = design.entity
    harness = timing_harness_vhdl(design)
    harness_rel = f"synth/{e}_timed.vhd"
    project.write(harness_rel, harness, "timing_harness")
    build = Path(project.root) / "build"
    build.mkdir(exist_ok=True)
    netlist = build / f"{e}.json"
    report = build / f"{e}_nextpnr.json"
    log = ""

    ys = (f"plugin -i ghdl; "
          f"ghdl --std=08 rtl/{e}.vhd {harness_rel} -e {e}_timed; "
          f"synth_ice40 -top {e}_timed -json {netlist}")
    try:
        y = subprocess.run(["yosys", "-p", ys], cwd=str(project.root),
                           capture_output=True, text=True, timeout=timeout)
    except Exception as exc:
        return PnrResult(False, reason=f"yosys invocation failed: {exc}")
    log += y.stdout + y.stderr
    if y.returncode != 0 or not netlist.exists():
        return PnrResult(False, log=log, reason="yosys/GHDL synthesis failed (see log)")
    luts = _count(log, r"\bSB_LUT4\b\s+(\d+)")
    ffs = _count(log, r"\bSB_DFF\w*\b\s+(\d+)", total=True)

    try:
        n = subprocess.run(["nextpnr-ice40", f"--{DEVICE}", "--package", "sg48",
                            "--json", str(netlist), "--report", str(report),
                            "--pcf-allow-unconstrained",
                            "--freq", str(FREQ_TARGET_MHZ), "--seed", str(SEED)],
                           cwd=str(project.root), capture_output=True, text=True,
                           timeout=timeout)
    except Exception as exc:
        return PnrResult(False, log=log, reason=f"nextpnr invocation failed: {exc}")
    log += n.stdout + n.stderr
    if n.returncode != 0 or not report.exists():
        return PnrResult(False, log=log, reason="nextpnr place-and-route failed (see log)")

    fmax = _fmax_from_report(report)
    if fmax is None:
        return PnrResult(False, log=log, reason="no fmax in nextpnr report")
    qor = QoR(luts=luts or 0, registers=ffs or 0, dsp=0,
              critical_path_ns=round(1000.0 / fmax, 2) if fmax else 0.0,
              fmax_mhz=round(fmax, 1), source="nextpnr-ice40")
    return PnrResult(True, qor, log, harness_path=harness_rel,
                     report_path=str(report.relative_to(project.root)))


def _count(log: str, pattern: str, total: bool = False) -> int | None:
    import re
    m = re.findall(pattern, log)
    if not m:
        return None
    vals = [int(x) for x in m]
    return sum(vals) if total else max(vals)


def _fmax_from_report(report: Path) -> float | None:
    try:
        data = json.loads(report.read_text())
        fmax = data.get("fmax") or {}
        achieved = [v.get("achieved") for v in fmax.values()
                    if isinstance(v, dict) and v.get("achieved")]
        return min(achieved) if achieved else None   # design Fmax = slowest clock
    except Exception:
        return None
